services:
  cloudflare_ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare_ddns
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: UTC
      API_KEY: ${CLOUDFLARE_DDNS_KEY:?Error Set cloudflare token}
      ZONE: ${BASE_DOMAIN:?Set base domain}
      SUBDOMAIN: "db.lab"
      PROXIED: "false"
      RRTYPE: A
      CUSTOM_LOOKUP_CMD: "ip route get 1.1.1.1 | awk '{print $7; exit}'"

  postgres:
    image: "postgres:18.3"
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - postgres_data:/var/lib/postgresql

  opensearch:
    image: opensearchproject/opensearch:3.5.0
    container_name: opensearch
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_data:/usr/share/opensearch/data

volumes:
  postgres_data:
    driver: local
    name: postgres_data
  opensearch_data:
    driver: local
    name: opensearch_data
