---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-ddns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns-home
  namespace: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns-home
  template:
    metadata:
      labels:
        app: cloudflare-ddns-home
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: cloudflare-ddns
          image: oznu/cloudflare-ddns:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns
                  key: API_KEY
            - name: ZONE
              value: "${BASE_DOMAIN:=example.com}"
            - name: SUBDOMAIN
              value: "*.home"
            - name: RRTYPE
              value: "A"
            - name: PROXIED
              value: "false"
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CUSTOM_LOOKUP_CMD
              value: "echo $HOST_IP"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
