---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 1.0h
  chart:
    spec:
      chart: csi-driver-nfs
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
      version: "v4.12.0"
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    externalProvisioner:
      enabled: true
    externalAttacher:
      enabled: true
    externalResizer:
      enabled: true
    snapshotter:
      enabled: true