apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs.home.${BASE_DOMAIN:=example.com}
  share: /srv/nfs/k8s
  subDir: $${pvc.metadata.namespace}-$${pvc.metadata.name}
  mountPermissions: "0777"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
