apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-synology-media-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: nas.lab.${BASE_DOMAIN:=example.com}#/volume4/media#
    volumeAttributes:
      server: nas.lab.${BASE_DOMAIN:=example.com}
      share: /volume4/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-media-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: pv-synology-media-nfs
  storageClassName: nfs-media
