---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 10m
  releaseName: airflow
  chart:
    spec:
      chart: airflow
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: airflow
        namespace: flux-system

  values:
    # <- Must have block for flux -->
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false
    # <- End must have block ------->
    executor: LocalExecutor
    useStandardNaming: true
