---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jellyfin.yaml
  - transmission.yaml
  - proxy.yaml
  - searxng.yaml
  - crawl4ai.yaml
  - sonarr.yaml
  - prowlarr.yaml
  - lidarr.yaml
  - radarr.yaml
  - seerr.yaml
  # - airflow-helmrelease.yaml
